package net.spartanb312.grunt.ir.flow.core

import org.objectweb.asm.tree.AbstractInsnNode

/**
 * Opaque bytecode island.
 *
 * Flow IR does not model ordinary JVM operations. It keeps them in slices and
 * only abstracts the terminal jump node that controls outgoing edges.
 */
class FlowBytecodeSlice(
    val instructions: MutableList<AbstractInsnNode> = mutableListOf()
) {
    val size get() = instructions.size
    val isEmpty get() = instructions.isEmpty()

    fun append(instruction: AbstractInsnNode): FlowBytecodeSlice {
        instructions += instruction
        return this
    }

    fun appendAll(nodes: Iterable<AbstractInsnNode>): FlowBytecodeSlice {
        instructions += nodes
        return this
    }
}

/** Reusable generated bytecode with explicit frame contract. */
data class FlowSnippet(
    val code: FlowBytecodeSlice,
    val entryFrame: FlowFrame,
    val exitFrame: FlowFrame,
    val effect: FlowSnippetEffect = FlowSnippetEffect.Pure,
    val mayThrow: Boolean = false
)

enum class FlowSnippetEffect {
    Pure,
    ReadsLocals,
    WritesLocals,
    SideEffecting
}
